apiVersion: v1
kind: Service
metadata:
  name: hellogo
spec:
  ports:
  - name: tcp-hellogo
    port: 8080
    protocol: TCP
    targetPort: tcp-hellogo
  selector:
    app: landing-page
  type: ClusterIP